title: My love - Tyn
email: 281028903@qq.com
description: > # this means to ignore newlines until "baseurl:"
  很爱很爱你
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: xxh # add your name
author-pic: myface.jpg
about-author: 很久很久..

# Contact links
email: 281028903@qq.com# Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: 94xxh # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: bigxlovetyn # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
